SmartFactorySimulator/SmartFactory/config/routes.rb
Rails.application.routes.draw do
  resources :machines
  resources :new_coms
  resources :inputs

  get 'original_total_result' => 'simulator#original_result'
  get 'smart_grid' => 'simulator#smart_grid_gen'
  get 'smart_grid_result' => 'simulator#smart_grid_result'
  get 'compare' => 'simulator#comparison_gen'
  get 'setting' => 'inputs#settings'
  get 'input_volume_data' => 'simulator#input_volume_data'
  get 'index' => 'simulator#index'
  root 'simulator#title'

end

SmartFactorySimulator/SmartFactory/app/models/new_com.rb
class NewCom < ActiveRecord::Base
end

SmartFactorySimulator/SmartFactory/app/controllers/new_coms_controller.rb
class NewComsController < ApplicationController
  before_action :set_new_com, only: [:show, :edit, :update, :destroy]

  # GET /new_coms
  # GET /new_coms.json
  def index
    @new_coms = NewCom.all
  end

  # GET /new_coms/1
  # GET /new_coms/1.json
  def show
  end

  # GET /new_coms/new
  def new
    @new_com = NewCom.new
  end

  # GET /new_coms/1/edit
  def edit
  end

  # POST /new_coms
  # POST /new_coms.json
  def create
    @new_com = NewCom.new(new_com_params)

    respond_to do |format|
      if @new_com.save
        format.html { redirect_to @new_com, notice: 'New com was successfully created.' }
        format.json { render :show, status: :created, location: @new_com }
      else
        format.html { render :new }
        format.json { render json: @new_com.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /new_coms/1
  # PATCH/PUT /new_coms/1.json
  def update
    respond_to do |format|
      if @new_com.update(new_com_params)
        format.html { redirect_to @new_com, notice: 'New com was successfully updated.' }
        format.json { render :show, status: :ok, location: @new_com }
      else
        format.html { render :edit }
        format.json { render json: @new_com.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /new_coms/1
  # DELETE /new_coms/1.json
  def destroy
    @new_com.destroy
    respond_to do |format|
      format.html { redirect_to new_coms_url, notice: 'New com was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_new_com
      @new_com = NewCom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def new_com_params
      params.require(:new_com).permit(:level, :portion, :power, :max_flow)
    end
end

SmartFactorySimulator/SmartFactory/app/helpers/new_coms_helper.rb
module NewComsHelper
end

SmartFactorySimulator/SmartFactory/app/views/new_coms/_form.html.erb
<%= form_for(@new_com) do |f| %>
  <% if @new_com.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@new_com.errors.count, "error") %> prohibited this new_com from being saved:</h2>

      <ul>
      <% @new_com.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :level %><br>
    <%= f.number_field :level %>
  </div>
  <div class="field">
    <%= f.label :portion %><br>
    <%= f.number_field :portion %>
  </div>
  <div class="field">
    <%= f.label :power %><br>
    <%= f.text_field :power %>
  </div>
  <div class="field">
    <%= f.label :max_flow %><br>
    <%= f.text_field :max_flow %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SmartFactorySimulator/SmartFactory/app/views/new_coms/edit.html.erb
<h1>Editing New Com</h1>

<%= render 'form' %>

<%= link_to 'Show', @new_com %> |
<%= link_to 'Back', inputs_path %>

SmartFactorySimulator/SmartFactory/app/views/new_coms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing New Coms</h1>

<table>
  <thead>
    <tr>
      <th>Level</th>
      <th>Portion</th>
      <th>Power</th>
      <th>Max flow</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @new_coms.each do |new_com| %>
      <tr>
        <td><%= new_com.level %></td>
        <td><%= new_com.portion %></td>
        <td><%= new_com.power %></td>
        <td><%= new_com.max_flow %></td>
        <td><%= link_to 'Show', new_com %></td>
        <td><%= link_to 'Edit', edit_new_com_path(new_com) %></td>
        <td><%= link_to 'Destroy', new_com, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New New com', new_new_com_path %>

SmartFactorySimulator/SmartFactory/app/views/new_coms/new.html.erb
<h1>New New Com</h1>

<%= render 'form' %>

<%= link_to 'Back', new_coms_path %>

SmartFactorySimulator/SmartFactory/app/views/new_coms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Level:</strong>
  <%= @new_com.level %>
</p>

<p>
  <strong>Portion:</strong>
  <%= @new_com.portion %>
</p>

<p>
  <strong>Power:</strong>
  <%= @new_com.power %>
</p>

<p>
  <strong>Max flow:</strong>
  <%= @new_com.max_flow %>
</p>

<%= link_to 'Edit', edit_new_com_path(@new_com) %> |
<%= link_to 'Back', inputs_path %>