SmartFactorySimulator/SmartFactory/config/routes.rb
Rails.application.routes.draw do
  resources :machines
  resources :new_coms
  resources :inputs

  get 'original_total_result' => 'simulator#original_result'
  get 'smart_grid' => 'simulator#smart_grid_gen'
  get 'smart_grid_result' => 'simulator#smart_grid_result'
  get 'compare' => 'simulator#comparison_gen'
  get 'setting' => 'inputs#settings'
  get 'input_volume_data' => 'simulator#input_volume_data'
  get 'index' => 'simulator#index'
  root 'simulator#title'

end

SmartFactorySimulator/SmartFactory/app/models/input.rb
class Input < ActiveRecord::Base
  private
    def input_params
          params.require(:input).permit(:fixed_flow)
    end
end

SmartFactorySimulator/SmartFactory/app/controllers/inputs_controller.rb
class InputsController < ApplicationController
  before_action :set_input, only: [:show, :edit, :update, :destroy]

  # GET /inputs
  # GET /inputs.json
  def index
    @inputs = Input.all
    @new_coms = NewCom.all
    @NewComs = NewCom.all
    @portion = []
    v = 0
    @NewComs.reverse.each do |c|
       @portion.push c.portion - v
       v = c.portion
    end
    @portion = @portion.reverse
    @machines = Machine.all
    @input = Input.first
  end

  def settings
    @input = Input.first
    @NewComs = NewCom.all
    @portion = []
    v = 0
    @NewComs.reverse.each do |c|
      @portion.push c.portion - v
      v = c.portion
    end
    @portion = @portion.reverse
    render "settings",:layout => false 
    
  end

  # GET /inputs/1
  # GET /inputs/1.json
  def show
  end

  # GET /inputs/new
  def new
    @input = Input.new
  end

  # GET /inputs/1/edit
  def edit
  end

  # POST /inputs
  # POST /inputs.json
  def create
    @input = Input.new(input_params)

    respond_to do |format|
      if @input.save
        format.html { redirect_to @input, notice: 'Input was successfully created.' }
        format.json { render :show, status: :created, location: @input }
      else
        format.html { render :new }
        format.json { render json: @input.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inputs/1
  # PATCH/PUT /inputs/1.json
  def update
    if params["com"]
      keys = params["com"].keys.sort.reverse
      newcoms = NewCom.all.reverse
      v = 0
      keys.each_with_index do |k,i|
        com = params["com"][k]
        ncom = newcoms[i]
        ncom.level = com["level"]
        v = v + com["portion"].to_i
        ncom.portion = v
        ncom.power = com["power"]
        ncom.save!
      end
    end
    respond_to do |format|
      if @input.update(input_params)
        format.html { redirect_to action: "index", notice: 'Inputs are uploaded successfully'}
        format.json { render :show, status: :ok, location: @input }
      else
        format.html { render :edit }
        format.json { render json: @input.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inputs/1
  # DELETE /inputs/1.json
  def destroy
    @input.destroy
    respond_to do |format|
      format.html { redirect_to inputs_url, notice: 'Input was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_input
      @input = Input.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def input_params
      params.require(:input).permit(:energy_cost, :losses, :fixed_num, :variable_num, :fixed_power, :fixed_run, :fixed_idle, :var_min, :var_max, :var_power,:fixed_flow)
    end
end

SmartFactorySimulator/SmartFactory/app/helpers/inputs_helper.rb
module InputsHelper
end

SmartFactorySimulator/SmartFactory/app/views/inputs/_form.html.erb
<p id="notice"><%= notice %></p>
<h2> Common </h2>

<%= form_for @input , :id => "input_tag"  do |f| %>
<div class="col-xs-6">
	<div class="col-xs-4">
		<h3> Energy cost: </h3>
	</div>
	<div class="col-xs-6">
		<div class="input-group input-group-sm">
      <%= f.number_field :energy_cost, :step => 'any' , :class => "form-control"%>
			<span class="input-group-addon"> KRW/kWh </span>
		</div>
	</div>
</div>
<div class="col-xs-6">
	<div class="col-xs-4">
		<h3> Losses: </h3>
	</div>
	<div class="col-xs-6">
		<div class="input-group input-group-sm">
          <%= f.number_field :losses, :step => 'any' ,:class => "form-control"%>
			<span class="input-group-addon"> % </span>
		</div>
	</div>
</div>
<div class="clearfix visible-xs-block visible-sm-block visible-md-block visible-lg-block"></div>

<hr>
<h2> Original </h2>

<div class="col-xs-6">
	<h3> Fixed characteristics</h3>	
	<div class="col-xs-4">
		<h3> # of machines: </h3>
	</div>
	<div class="col-xs-6">
		<div class="input-group input-group-sm">
      <%= f.text_field :fixed_num, :step => 'any',:class => "form-control" %>
		</div>
	</div>

	<div class="clearfix visible-xs-block visible-sm-block visible-md-block visible-lg-block"></div>
	<div class="col-xs-4">
		<h3> Flow: </h3>
	</div>
	<div class="col-xs-6">
		<div class="input-group input-group-sm">
      <%= f.text_field :fixed_flow, :step => 'any',:class => "form-control" %>
			<span class="input-group-addon"> m3/min </span>
		</div>
	</div>

	<div class="clearfix visible-xs-block visible-sm-block visible-md-block visible-lg-block"></div>
	<div class="col-xs-4">
		<h3> Running power: </h3>
	</div>
	<div class="col-xs-6">
		<div class="input-group input-group-sm">
      <%= f.text_field :fixed_run, :step => 'any',:class => "form-control" %>
			<span class="input-group-addon"> kW </span>
		</div>
	</div>

	<div class="clearfix visible-xs-block visible-sm-block visible-md-block visible-lg-block"></div>
	<div class="col-xs-4">
		<h3> Idle power: </h3>
	</div>
	<div class="col-xs-6">
		<div class="input-group input-group-sm">
      <%= f.text_field :fixed_idle, :step => 'any',:class => "form-control" %>
			<span class="input-group-addon"> kW </span>
		</div>
	</div>
</div>

<div class="col-xs-6">
	<h3> Variable characteristics</h3>	
	<div class="col-xs-4">
		<h3> # of machines: </h3>
	</div>
	<div class="col-xs-6">
		<div class="input-group input-group-sm">
      <%= f.text_field :variable_num, :step => 'any',:class => "form-control" %>
		</div>
	</div>

	<div class="clearfix visible-xs-block visible-sm-block visible-md-block visible-lg-block"></div>
	<div class="col-xs-4">
		<h3> Maximum flow: </h3>
	</div>
	<div class="col-xs-6">
		<div class="input-group input-group-sm">
      <%= f.text_field :var_max, :step => 'any',:class => "form-control" %>
			<span class="input-group-addon"> m3/min </span>
		</div>
	</div>

	<div class="clearfix visible-xs-block visible-sm-block visible-md-block visible-lg-block"></div>
	<div class="col-xs-4">
		<h3> Minimum flow: </h3>
	</div>
	<div class="col-xs-6">
		<div class="input-group input-group-sm">
      <%= f.text_field :var_min, :step => 'any',:class => "form-control" %>
			<span class="input-group-addon"> m3/min </span>
		</div>
	</div>

	<div class="clearfix visible-xs-block visible-sm-block visible-md-block visible-lg-block"></div>
	<div class="col-xs-4">
		<h3> Specific performance: </h3>
	</div>
	<div class="col-xs-6">
		<div class="input-group input-group-sm">
      <%= f.text_field :var_power, :step => 'any',:class => "form-control" %>
			<span class="input-group-addon"> kW/m3/min </span>
		</div>
	</div>
</div>

<div class="clearfix visible-xs-block visible-sm-block visible-md-block visible-lg-block"></div>
<hr>
<h2> Proposed </h2>
<div class="col-xs-2"></div>
<div class="col-xs-2"><h3>Type-1</h3></div>
<div class="col-xs-2"><h3>Type-2</h3></div>
<div class="col-xs-2"><h3>Type-3</h3></div>
<div class="col-xs-2"><h3>Type-4</h3></div>
<div class="clearfix visible-xs-block visible-sm-block visible-md-block visible-lg-block"></div>

<div class="col-xs-2">
	<h3> Compressor level: </h3>
</div>
<% @NewComs.each do |c|%>
  <div class="col-xs-2">
    <div class="input-group input-group-sm">
      <input name="com[<%=c.level%>][level]"type="text" class="form-control" value="<%= c.level %>">
      <span class="input-group-addon"> bar abs </span>
    </div>
  </div>
<% end %>
<div class="clearfix visible-xs-block visible-sm-block visible-md-block visible-lg-block"></div>

<div class="col-xs-2">
	<h3> Volume portion: </h3>
</div>
<% @NewComs.each_with_index do |c,i|%>
  <div class="col-xs-2">
    <div class="input-group input-group-sm">
      <input name="com[<%=c.level%>][portion]" type="text" class="form-control" value="<%=@portion[i]%>">
      <span class="input-group-addon"> % </span>
    </div>
  </div>
<% end %>
<div class="clearfix visible-xs-block visible-sm-block visible-md-block visible-lg-block"></div>

<div class="col-xs-2">
	<h3> Maximum flow: </h3>
</div>
<% @NewComs.each do |c|%>
  <div class="col-xs-2">
    <div class="input-group input-group-sm">
      <input name="com[<%=c.level%>][max_flow]" type="text" class="form-control" value="<%=c.max_flow%>">
      <span class="input-group-addon"> m3/min </span>
    </div>
  </div>
<% end %>
<div class="clearfix visible-xs-block visible-sm-block visible-md-block visible-lg-block"></div>

<div class="col-xs-2">
	<h3> Specific performance: </h3>
</div>
<% @NewComs.each do |c|%>
  <div class="col-xs-2" >
    <div class="input-group input-group-sm">
      <input name="com[<%=c.level%>][power]" type="text" class="form-control" value="<%=c.power%>">
      <span class="input-group-addon"> kW/m3/min </span>
    </div>
  </div>
<% end %>
<br></br>
<hr></hr>
<%= f.submit :class => "btn btn-default"%>


<% end %>

SmartFactorySimulator/SmartFactory/app/views/inputs/edit.html.erb
<h1>Editing Input</h1>

<%= render 'form' %>

<%= link_to 'Show', @input %> |
<%= link_to 'Back', inputs_path %>

SmartFactorySimulator/SmartFactory/app/views/inputs/index.html.erb
<%= render 'form' %>

SmartFactorySimulator/SmartFactory/app/views/inputs/new.html.erb
<h1>New Input</h1>

<%= render 'form' %>

<%= link_to 'Back', inputs_path %>

SmartFactorySimulator/SmartFactory/app/views/inputs/settings.html.erb
<h2> Common </h2>
<div class="col-xs-6">
	<div class="col-xs-4">
		<h3> Energy cost: </h3>
	</div>
	<div class="col-xs-6">
		<div class="input-group input-group-sm">
      <input type="text" class="form-control" placeholder="" value="<%=@input.energy_cost%>">
			<span class="input-group-addon"> KRW/kWh </span>
		</div>
	</div>
</div>

<div class="col-xs-6">
	<div class="col-xs-4">
		<h3> Losses: </h3>
	</div>
	<div class="col-xs-6">
		<div class="input-group input-group-sm">
      <input type="text" class="form-control" placeholder="" value="<%=@input.losses%>">
			<span class="input-group-addon"> % </span>
		</div>
	</div>
</div>
<div class="clearfix visible-xs-block visible-sm-block visible-md-block visible-lg-block"></div>

<hr>
<h2> Original </h2>
<div class="col-xs-6">
	<h3> Fixed machines</h3>	
	<div class="col-xs-4">
		<h3> # of machines: </h3>
	</div>
	<div class="col-xs-6">
		<div class="input-group input-group-sm">
      <input type="text" class="form-control" placeholder="<%=@input.fixed_num%>">
		</div>
	</div>

	<div class="clearfix visible-xs-block visible-sm-block visible-md-block visible-lg-block"></div>
	<div class="col-xs-4">
		<h3> Flow: </h3>
	</div>
	<div class="col-xs-6">
		<div class="input-group input-group-sm">
			<input type="text" class="form-control" placeholder="<%=@input.fixed_flow%>">
			<span class="input-group-addon"> m3/min </span>
		</div>
	</div>

	<div class="clearfix visible-xs-block visible-sm-block visible-md-block visible-lg-block"></div>
	<div class="col-xs-4">
		<h3> Running power: </h3>
	</div>
	<div class="col-xs-6">
		<div class="input-group input-group-sm">
			<input type="text" class="form-control" placeholder="<%=@input.fixed_run%>">
			<span class="input-group-addon"> kW </span>
		</div>
	</div>

	<div class="clearfix visible-xs-block visible-sm-block visible-md-block visible-lg-block"></div>
	<div class="col-xs-4">
		<h3> Idle power: </h3>
	</div>
	<div class="col-xs-6">
		<div class="input-group input-group-sm">
			<input type="text" class="form-control" placeholder="<%=@input.fixed_idle%>">
			<span class="input-group-addon"> kW </span>
		</div>
	</div>
</div>


<div class="col-xs-6">
	<h3> Variable machines</h3>	
	<div class="col-xs-4">
		<h3> # of machines: </h3>
	</div>
	<div class="col-xs-6">
		<div class="input-group input-group-sm">
			<input type="text" class="form-control" placeholder="<%=@input.variable_num%>">
		</div>
	</div>

	<div class="clearfix visible-xs-block visible-sm-block visible-md-block visible-lg-block"></div>
	<div class="col-xs-4">
		<h3> Minimum flow: </h3>
	</div>
	<div class="col-xs-6">
		<div class="input-group input-group-sm">
			<input type="text" class="form-control" placeholder="<%=@input.var_max%>">
			<span class="input-group-addon"> m3/min </span>
		</div>
	</div>

	<div class="clearfix visible-xs-block visible-sm-block visible-md-block visible-lg-block"></div>
	<div class="col-xs-4">
		<h3> Maximum flow: </h3>
	</div>
	<div class="col-xs-6">
		<div class="input-group input-group-sm">
			<input type="text" class="form-control" placeholder="<%=@input.var_min%>">
			<span class="input-group-addon"> m3/min </span>
		</div>
	</div>

	<div class="clearfix visible-xs-block visible-sm-block visible-md-block visible-lg-block"></div>
	<div class="col-xs-4">
		<h3> Specific power: </h3>
	</div>
	<div class="col-xs-6">
		<div class="input-group input-group-sm">
			<input type="text" class="form-control" placeholder="<%=@input.var_power%>">
			<span class="input-group-addon"> kW/m3/min </span>
		</div>
	</div>
</div>

<div class="clearfix visible-xs-block visible-sm-block visible-md-block visible-lg-block"></div>
<hr>
<h2> Proposed </h2>
<div class="col-xs-2"></div>
<div class="col-xs-2"><h3>Type-1</h3></div>
<div class="col-xs-2"><h3>Type-2</h3></div>
<div class="col-xs-2"><h3>Type-3</h3></div>
<div class="col-xs-2"><h3>Type-4</h3></div>
<div class="clearfix visible-xs-block visible-sm-block visible-md-block visible-lg-block"></div>

<div class="col-xs-2">
	<h3> Compressor level: </h3>
</div>
<% @NewComs.each do |c|%>
  <div class="col-xs-2">
    <div class="input-group input-group-sm">
      <input type="text" class="form-control" placeholder="<%= c.level %>">
      <span class="input-group-addon"> bar abs </span>
    </div>
  </div>
<% end %>
<div class="clearfix visible-xs-block visible-sm-block visible-md-block visible-lg-block"></div>

<div class="col-xs-2">
	<h3> Volume portion: </h3>
</div>
<% @portion.each do |c|%>
  <div class="col-xs-2">
    <div class="input-group input-group-sm">
      <input type="text" class="form-control" placeholder="<%=c%>">
      <span class="input-group-addon"> % </span>
    </div>
  </div>
<% end %>
<div class="clearfix visible-xs-block visible-sm-block visible-md-block visible-lg-block"></div>

<div class="col-xs-2">
	<h3> Maximum flow: </h3>
</div>
<% @NewComs.each do |c|%>
  <div class="col-xs-2">
    <div class="input-group input-group-sm">
      <input type="text" class="form-control" placeholder="<%=c.max_flow%>">
      <span class="input-group-addon"> m3/min </span>
    </div>
  </div>
<% end %>
<div class="clearfix visible-xs-block visible-sm-block visible-md-block visible-lg-block"></div>

<div class="col-xs-2">
	<h3> Specific power: </h3>
</div>
<% @NewComs.each do |c|%>
  <div class="col-xs-2">
    <div class="input-group input-group-sm">
      <input type="text" class="form-control" placeholder="<%=c.power%>">
      <span class="input-group-addon"> kW/m3/min </span>
    </div>
  </div>
<% end %>

SmartFactorySimulator/SmartFactory/app/views/inputs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Energy cost:</strong>
  <%= @input.energy_cost %>
</p>

<p>
  <strong>Losses:</strong>
  <%= @input.losses %>
</p>

<p>
  <strong>Fixed num:</strong>
  <%= @input.fixed_num %>
</p>

<p>
  <strong>Variable num:</strong>
  <%= @input.variable_num %>
</p>

<p>
  <strong>Fixed flow:</strong>
  <%= @input.fixed_flow %>
</p>

<p>
  <strong>Fixed run:</strong>
  <%= @input.fixed_run %>
</p>

<p>
  <strong>Fixed idle:</strong>
  <%= @input.fixed_idle %>
</p>

<p>
  <strong>Var min:</strong>
  <%= @input.var_min %>
</p>

<p>
  <strong>Var max:</strong>
  <%= @input.var_max %>
</p>

<p>
  <strong>Var power:</strong>
  <%= @input.var_power %>
</p>

<%= link_to 'Edit', edit_input_path(@input) %> |
<%= link_to 'Back', inputs_path %>