SmartFactorySimulator/SmartFactory/config/routes.rb
Rails.application.routes.draw do
  resources :machines
  resources :new_coms
  resources :inputs

  get 'original_total_result' => 'simulator#original_result'
  get 'smart_grid' => 'simulator#smart_grid_gen'
  get 'smart_grid_result' => 'simulator#smart_grid_result'
  get 'compare' => 'simulator#comparison_gen'
  get 'setting' => 'inputs#settings'
  get 'input_volume_data' => 'simulator#input_volume_data'
  get 'index' => 'simulator#index'
  root 'simulator#title'

end

SmartFactorySimulator/SmartFactory/app/models/machine.rb
class Machine < ActiveRecord::Base
end

SmartFactorySimulator/SmartFactory/app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  before_action :set_machine, only: [:show, :edit, :update, :destroy]

  # GET /machines
  # GET /machines.json
  def index
    @machines = Machine.all
  end

  # GET /machines/1
  # GET /machines/1.json
  def show
  end

  # GET /machines/new
  def new
    @machine = Machine.new
  end

  # GET /machines/1/edit
  def edit
  end

  # POST /machines
  # POST /machines.json
  def create
    @machine = Machine.new(machine_params)

    respond_to do |format|
      if @machine.save
        format.html { redirect_to @machine, notice: 'Machine was successfully created.' }
        format.json { render :show, status: :created, location: @machine }
      else
        format.html { render :new }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /machines/1
  # PATCH/PUT /machines/1.json
  def update
    respond_to do |format|
      if @machine.update(machine_params)
        format.html { redirect_to @machine, notice: 'Machine was successfully updated.' }
        format.json { render :show, status: :ok, location: @machine }
      else
        format.html { render :edit }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /machines/1
  # DELETE /machines/1.json
  def destroy
    @machine.destroy
    respond_to do |format|
      format.html { redirect_to machines_url, notice: 'Machine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_machine
      @machine = Machine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def machine_params
      params.require(:machine).permit(:kWh, :price)
    end
end

SmartFactorySimulator/SmartFactory/app/helpers/machines_helper.rb
module MachinesHelper
end

SmartFactorySimulator/SmartFactory/app/views/machines/_form.html.erb
<%= form_for(@machine) do |f| %>
  <% if @machine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@machine.errors.count, "error") %> prohibited this machine from being saved:</h2>

      <ul>
      <% @machine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :kWh %><br>
    <%= f.number_field :kWh %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SmartFactorySimulator/SmartFactory/app/views/machines/edit.html.erb
<h1>Editing Machine</h1>

<%= render 'form' %>

<%= link_to 'Show', @machine %> |
<%= link_to 'Back', inputs_path %>

SmartFactorySimulator/SmartFactory/app/views/machines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Machines</h1>

<table>
  <thead>
    <tr>
      <th>Kwh</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @machines.each do |machine| %>
      <tr>
        <td><%= machine.kWh %></td>
        <td><%= machine.price %></td>
        <td><%= link_to 'Show', machine %></td>
        <td><%= link_to 'Edit', edit_machine_path(machine) %></td>
        <td><%= link_to 'Destroy', machine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Machine', inputs_path %>

SmartFactorySimulator/SmartFactory/app/views/machines/new.html.erb
<h1>New Machine</h1>

<%= render 'form' %>

<%= link_to 'Back', machines_path %>

SmartFactorySimulator/SmartFactory/app/views/machines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Kwh:</strong>
  <%= @machine.kWh %>
</p>

<p>
  <strong>Price:</strong>
  <%= @machine.price %>
</p>

<%= link_to 'Edit', edit_machine_path(@machine) %> |
<%= link_to 'Back', machines_path %>